%This is a function that produces a stastical analysis of the data
%generated by my code compared to the solution output files. It takes as
%input the coordinates of the tip w.r.t. body B, the coordinates of 
%the points on the surface closest to the sample points, and the magnitude 
%of the difference between the two, generated by my code and the solution 
%text files, and produces a number of statistical
%comparisons. 

function [max_diff_d,mean_diff_d, stdev_diff_d, max_diff_c,mean_diff_c, stdev_diff_c, maxdiff_diff, meandiff_diff]=statisticalAnalysis_P4(d_sol, dk, c_sol, ck, diff_sol, diff)

ck_2D=three2twoDim(ck);
dk_2D=three2twoDim(dk);
nf=size(c_sol,2);

c_diff_mag=zeros(1,nf);
%We compute the difference in the positions of the closest point 
%of the solution and those generated by my code. 
c_diff=c_sol-ck_2D;
%The following for loop computes the magnitude of the difference in
%positions and stores it in a 1D array. 

for i=1:nf
    c_diff_mag(1,i)=norm(c_diff(:,i));
end


%We compute the max differnce observed, the mean differnece observed, and
%the standard deviations. 
max_diff_c=max(c_diff_mag);
mean_diff_c=mean(c_diff_mag);
stdev_diff_c=std(c_diff_mag);


%We compute the difference in the positions of the tip w.r.t body B, 
%of the solution and those generated by my code. 

d_diff_mag=zeros(1,nf);
d_diff=d_sol-dk_2D;
%The following for loops compute the magnitude of the difference in
%positions and store it in a 1D array. 

for i=1:nf
    d_diff_mag(1,i)=norm(d_diff(:,i));
end
    
%We compute the max differnce observed, the mean differnece observed, and
%the standard deviations. 
max_diff_d=max(d_diff_mag);
mean_diff_d=mean(d_diff_mag);
stdev_diff_d=std(d_diff_mag);


%we compute the max difference and mean difference in the difference 
%observed from the solution files and my code. 

diff_diff=abs(diff_sol-diff);

maxdiff_diff=max(diff_diff(1,:));
meandiff_diff=mean(diff_diff(1,:));
